title: "Muhaimin Khan"
description: "Final year Computer Engineering student. Personal e-portfolio."
author: "Muhaimin Khan"
email: "khnmuhaimin@gmail.com"

url: "https://khnmuhaimin.github.io"

theme: minima

# Navigation structure
header_pages:
  - about.md
  - projects.md
  - experience.md
  - skills.md
  - contact.md

markdown: kramdown
