title: "Muhaimin Khan"
description: "Final year Computer Engineering student. Personal e-portfolio."
author: "Muhaimin Khan"
email: "khnmuhaimin@gmail.com"

url: "https://khnmuhaimin.github.io"

theme: minima

# Navigation structure
header_pages:
  - about.md
  - projects.md
  - experience.md
  - skills.md
  - education.md
  - contact.md

markdown: kramdown

# Footer info
footer: >
  © 2025 Muhaimin Khan | 
  📧 [Email](mailto:khnmuhaimin@gmail.com) | 
  🔗 [LinkedIn](https://linkedin.com/in/muhaimin-khan-b825a425a) | 
  💼 [CV](assets/CV.pdf) <!-- placeholder for later -->

